config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root 'pages#home'

  get 'about' => "pages#about"
  get 'story' => "pages#story"

  resources :offers do
    resources :orders, only: [:new, :create]
  end

  resources :orders, except: [:new, :create] do
    get 'accept' => "orders#accept"
    get 'refuse' => "orders#refuse"
  end

  resources :users, :only => [:show]

  mount Attachinary::Engine => "/attachinary"

end

app/models/availability.rb
class Availability < ActiveRecord::Base
  belongs_to :offer
end

app/models/offer.rb
class Offer < ActiveRecord::Base
  has_many :orders
  belongs_to :owner, foreign_key: "user_id", class_name: "User"
  has_attachment :photo
  CATEGORIES = ["Dog", "Cat", "Fish"]
  PLACES = ["Apartment", "Garden", "Farm"]
  validates :title, presence: true
  validates :description, presence: true
  validates :address, presence: true
  validates :category, inclusion: {in: CATEGORIES}, presence: true
  validates :place_type, inclusion: {in: PLACES}, presence: true
  validates :price, presence: true
  validates :photo, presence: true
  geocoded_by :address
  after_validation :geocode, if: :address_changed?
  has_many :availabilities
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :renter, foreign_key: "user_id", class_name: "User"
  belongs_to :offer

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :orders
  has_many :offers

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, omniauth_providers: [:facebook]

  def self.find_for_facebook_oauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.first_name = auth.info.first_name
      user.last_name = auth.info.last_name
      user.picture = auth.info.image
      user.token = auth.credentials.token
      user.token_expiry = Time.at(auth.credentials.expires_at)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :authenticate_user!
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_action :set_offer, only: [ :show, :edit, :update, :destroy]

  def index
    @offers = Offer.where.not(latitude: nil)

    @category = params[:category]
    # @city = params[:city]
    @max_price = params[:max_price].to_i

    if @category
      @offers = @offers.where(category: @category)
    end
    # if @city
    #   @offers = @offers.where(city: @city)
    # end

    @markers = Gmaps4rails.build_markers(@offers) do |offer, marker|
      marker.lat offer.latitude
      marker.lng offer.longitude
      marker.infowindow render_to_string(:partial => "/offers/map_box", locals: {offer: offer})
    end
  end

  def show
    @alert_message = "You are viewing #{@offer.title}"
    @offer_coordinates = { lat: @offer.latitude, lng: @offer.longitude }
    @order = Order.new
  end

  def new
    @offer = Offer.new
  end

  def edit
  end

  def create
    @offer = Offer.new(offer_params)
    @offer.owner = current_user
    if @offer.save
      redirect_to offer_path(@offer)
    else
      render :new
    end
  end

  def update
    @offer.update(offer_params)
    redirect_to offer_path(@offer)
  end

  def destroy
    @offer.delete
    redirect_to offers_path
  end

  private
  def offer_params
    params.require(:offer).permit(:title, :description, :address, :place_type, :category, :price, :photo)
  end

  def set_offer
    @offer = Offer.find(params[:id])
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :find_offer, only: [ :new, :create]
  before_action :set_order, only: [:accept, :refuse]

  def accept
    @order.status = "accepted"
    @order.save
    redirect_to :back
  end

  def refuse
    @order.status = "refused"
    @order.save
    redirect_to :back
  end

 # GET "orders"
  def index
    @orders = Order.all
  end

  # GET "orders/42"
  def show
    @order = Order.find(params[:id])
  end

# GET "offers/42/orders/new"
  def new
    @order = Order.new
  end

# POST "offers/42/orders"
  def create
    @order = @offer.orders.build(order_params)
    @order.renter = current_user
    if  @order.save
      redirect_to user_path(current_user.id), notice: 'Successfully booked'
    else
      render :new
    end
  end

# DELETE "offers/42/orders/25"
  def destroy
    @order = Order.find(params[:id])
    @order.destroy
    respond_to do |format|
      format.html { redirect_to root, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def order_params
    params.require(:order).permit(:user_id, :offer_id, :start_date, :end_date)
  end

  def find_offer
    @offer = Offer.find(params[:offer_id])
  end

  def set_order
    @order = Order.find(params[:order_id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
    @offer = Offer.new
  end

  def about
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    user = User.find_for_facebook_oauth(request.env['omniauth.auth'])

    if user.persisted?
      sign_in_and_redirect user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      flash[:alert] = "We need your email"
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 before_action :set_user, only: [:show, :edit, :update, :destroy]
  # def index
  #   @users = User.all
  # end

 def show
    @petsing = @user.orders

  end

  # def new
  #   @user = User.new
  # end

  # def edit
  # end

  # def create
  #   @user = user.new(user_params)
  #   if @user.save
  #     redirect_to user_path(@user)
  #   else
  #     render :new
  #   end
  # end

  # def update
  #   @user.update(user_params)
  #   redirect_to user_path(@offer)
  # end

  # def destroy
  #   @user.delete
  #   redirect_to users_path
  # end

  private
  def user_params
    params.require(:user).permit(:email,:password)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/offers/_map_box.html.erb
<div class="map_box">
  <h3><%= offer.title %></h3>
  <p><%= offer.address %></p>
  <%= link_to "See", offer, class: "btn btn-warning" %>
</div>

app/views/offers/edit.html.erb
<%= render 'form' %>

app/views/offers/index.erb
<div class="bg-lighter-grey">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-8">
        <%= render 'pages/form_for' %>
      </div>
      <div class="col-xs-12 col-sm-8">
        <div id="map" class="fixed_map" style="width: 100%; height: 600px; max-height: 80%;"></div>
      </div>
      <div class="col-xs-12 col-sm-4">
        <h1>Search result</h1>
        <% if @offers.empty? %>
         <p>No record found</p>
        <% else %>
          <% @offers.each do |offer| %>
            <div class="card_main_index" style="background: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(
              <% if offer.photo.present? %>
                <%='http://res.cloudinary.com/doosfknzw/image/upload/' + offer.photo.path %>
              <% else %>
                'http://static1.businessinsider.com/image/5588455c69bedd63541b9b5b-1200/wong-wanted-to-help-seibel-make-the-apartment-feel-more-inviting-we-tempered-the-architecture-finishes-of-the-loft-with-softer-furnishings-and-materials-he-told-business-insider-we-blended-their-love-of-reclaimed-wood-and-metal-with-shag-rugs-quilted-chairs-leather-and-velvet.jpg'
              <% end %>
            );">
            <%= link_to(offer_path(offer)) do %>
              <h2 class="offer_main_title"><%= offer.title %></h2>
            <% end %>
            <p class="offer_main_price"><%= offer.price %>‎ € / day</p>
            <p class="offer_main_category"><%= offer.category %>‎ sitting</p>

            <% if offer.owner == current_user %>
              <%= link_to(edit_offer_path(offer)) do %>
                <i class="fa fa-pencil offer_edit"></i>
              <% end %>
              <%= link_to(offer_path(offer), method: :delete, data: {confirm: "Are you sure?"}) do %>
                <i class="fa fa-trash-o offer_delete"></i>
              <% end %>
            <% end %>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<% content_for(:after_js) do %>
  <script>
    $(document).on('ready', function() {
      handler = Gmaps.build('Google');
      handler.buildMap({ internal: { id: 'map' }, provider: { styles: [
        {
            "featureType": "landscape.man_made",
            "elementType": "geometry",
            "stylers": [
                {
                    "color": "#f7f1df"
                }
            ]
        },
        {
            "featureType": "landscape.natural",
            "elementType": "geometry",
            "stylers": [
                {
                    "color": "#d0e3b4"
                }
            ]
        },
        {
            "featureType": "landscape.natural.terrain",
            "elementType": "geometry",
            "stylers": [
                {
                    "visibility": "off"
                }
            ]
        },
        {
            "featureType": "poi",
            "elementType": "labels",
            "stylers": [
                {
                    "visibility": "off"
                }
            ]
        },
        {
            "featureType": "poi.business",
            "elementType": "all",
            "stylers": [
                {
                    "visibility": "off"
                }
            ]
        },
        {
            "featureType": "poi.medical",
            "elementType": "geometry",
            "stylers": [
                {
                    "color": "#fbd3da"
                }
            ]
        },
        {
            "featureType": "poi.park",
            "elementType": "geometry",
            "stylers": [
                {
                    "color": "#bde6ab"
                }
            ]
        },
        {
            "featureType": "road",
            "elementType": "geometry.stroke",
            "stylers": [
                {
                    "visibility": "off"
                }
            ]
        },
        {
            "featureType": "road",
            "elementType": "labels",
            "stylers": [
                {
                    "visibility": "off"
                }
            ]
        },
        {
            "featureType": "road.highway",
            "elementType": "geometry.fill",
            "stylers": [
                {
                    "color": "#ffe15f"
                }
            ]
        },
        {
            "featureType": "road.highway",
            "elementType": "geometry.stroke",
            "stylers": [
                {
                    "color": "#efd151"
                }
            ]
        },
        {
            "featureType": "road.arterial",
            "elementType": "geometry.fill",
            "stylers": [
                {
                    "color": "#ffffff"
                }
            ]
        },
        {
            "featureType": "road.local",
            "elementType": "geometry.fill",
            "stylers": [
                {
                    "color": "black"
                }
            ]
        },
        {
            "featureType": "transit.station.airport",
            "elementType": "geometry.fill",
            "stylers": [
                {
                    "color": "#cfb2db"
                }
            ]
        },
        {
            "featureType": "water",
            "elementType": "geometry",
            "stylers": [
                {
                    "color": "#a2daf2"
                }
            ]
        }
      ]} }, function(){
        markers = handler.addMarkers(<%= raw @markers.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
      });
    })
  </script>
<% end %>

app/views/offers/index.html.erb
<div class="bg-lighter-grey">
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-8">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Map</h3>
          </div>
          <div class="panel-body">
            <div id="map" style="height: 100%;"></div>
          </div>
        </div>
      </div>
      <div class="col-xs-12 col-sm-4">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Search result</h3>
          </div>
          <div class="panel-body" id="search-results">
            <% if @offers.empty? %>
             <p>No record found</p>
            <% else %>
              <% @offers.each do |offer| %>
                <div class="card_main_index" style="background: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(
                  <% if offer.photo.present? %>
                    <%='http://res.cloudinary.com/doosfknzw/image/upload/' + offer.photo.path %>
                  <% else %>
                    'http://static1.businessinsider.com/image/5588455c69bedd63541b9b5b-1200/wong-wanted-to-help-seibel-make-the-apartment-feel-more-inviting-we-tempered-the-architecture-finishes-of-the-loft-with-softer-furnishings-and-materials-he-told-business-insider-we-blended-their-love-of-reclaimed-wood-and-metal-with-shag-rugs-quilted-chairs-leather-and-velvet.jpg'
                  <% end %>
                );">
                <%= link_to(offer_path(offer)) do %>
                  <h2 class="offer_main_title"><%= offer.title %></h2>
                <% end %>
                <p class="offer_main_price"><%= offer.price %>‎ € / day</p>
                <p class="offer_main_category"><%= offer.category %>‎ sitting</p>

                <% if offer.owner == current_user %>
                  <%= link_to(edit_offer_path(offer)) do %>
                    <i class="fa fa-pencil offer_edit"></i>
                  <% end %>
                  <%= link_to(offer_path(offer), method: :delete, data: {confirm: "Are you sure?"}) do %>
                    <i class="fa fa-trash-o offer_delete"></i>
                  <% end %>
                <% end %>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>


<% content_for(:after_js) do %>
  <script>
    $(document).on('ready', function() {
      handler = Gmaps.build('Google');
      handler.buildMap({ internal: { id: 'map' }, provider: { styles: [
        {
            "featureType": "landscape.man_made",
            "elementType": "geometry",
            "stylers": [
                {
                    "color": "#f7f1df"
                }
            ]
        },
        {
            "featureType": "landscape.natural",
            "elementType": "geometry",
            "stylers": [
                {
                    "color": "#d0e3b4"
                }
            ]
        },
        {
            "featureType": "landscape.natural.terrain",
            "elementType": "geometry",
            "stylers": [
                {
                    "visibility": "off"
                }
            ]
        },
        {
            "featureType": "poi",
            "elementType": "labels",
            "stylers": [
                {
                    "visibility": "off"
                }
            ]
        },
        {
            "featureType": "poi.business",
            "elementType": "all",
            "stylers": [
                {
                    "visibility": "off"
                }
            ]
        },
        {
            "featureType": "poi.medical",
            "elementType": "geometry",
            "stylers": [
                {
                    "color": "#fbd3da"
                }
            ]
        },
        {
            "featureType": "poi.park",
            "elementType": "geometry",
            "stylers": [
                {
                    "color": "#bde6ab"
                }
            ]
        },
        {
            "featureType": "road",
            "elementType": "geometry.stroke",
            "stylers": [
                {
                    "visibility": "off"
                }
            ]
        },
        {
            "featureType": "road",
            "elementType": "labels",
            "stylers": [
                {
                    "visibility": "off"
                }
            ]
        },
        {
            "featureType": "road.highway",
            "elementType": "geometry.fill",
            "stylers": [
                {
                    "color": "#ffe15f"
                }
            ]
        },
        {
            "featureType": "road.highway",
            "elementType": "geometry.stroke",
            "stylers": [
                {
                    "color": "#efd151"
                }
            ]
        },
        {
            "featureType": "road.arterial",
            "elementType": "geometry.fill",
            "stylers": [
                {
                    "color": "#ffffff"
                }
            ]
        },
        {
            "featureType": "road.local",
            "elementType": "geometry.fill",
            "stylers": [
                {
                    "color": "black"
                }
            ]
        },
        {
            "featureType": "transit.station.airport",
            "elementType": "geometry.fill",
            "stylers": [
                {
                    "color": "#cfb2db"
                }
            ]
        },
        {
            "featureType": "water",
            "elementType": "geometry",
            "stylers": [
                {
                    "color": "#a2daf2"
                }
            ]
        }
      ]} }, function(){
        markers = handler.addMarkers(<%= raw @markers.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
      });
    })
  </script>
<% end %>

app/views/offers/new.html.erb
<%= render 'form' %>

app/views/offers/show.html.erb
<div class="bg-lighter-grey">
  <div class="container text-center">
    <div class="row">

      <div class="col-xs-12 col-sm-8 col-sm-offset-2">
        <div class="box">

          <div class="card_main_show" style="background: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(
            <% if @offer.photo.present? %>
              <%='http://res.cloudinary.com/doosfknzw/image/upload/' + @offer.photo.path %>
            <% else %>
              'http://static1.businessinsider.com/image/5588455c69bedd63541b9b5b-1200/wong-wanted-to-help-seibel-make-the-apartment-feel-more-inviting-we-tempered-the-architecture-finishes-of-the-loft-with-softer-furnishings-and-materials-he-told-business-insider-we-blended-their-love-of-reclaimed-wood-and-metal-with-shag-rugs-quilted-chairs-leather-and-velvet.jpg'
            <% end %>
          );">
            <h2 class="offer_main_title"><%= @offer.title %></h2>
            <p class="offer_main_price"><%= @offer.price %>‎ € / day</p>
            <p class="offer_main_category"><%= @offer.category %>‎ sitting</p>

            <% if @offer.owner == current_user %>
              <%= link_to(edit_offer_path(@offer)) do %>
                <i class="fa fa-pencil offer_edit"></i>
              <% end %>
              <%= link_to(offer_path(@offer), method: :delete, data: {confirm: "Are you sure?"}) do %>
                <i class="fa fa-trash-o offer_delete"></i>
              <% end %>
            <% end %>



          </div>
        </div>
        <div class="main_description">
          <p><%= @offer.description %>‎</p>
        </div>
        <div class="padded-small">
          <ul class="list-inline">
            <% if !current_user.offers.include? @offer %>
              <li>
                <button type="button" class="btn btn-success" data-toggle="modal" data-target="#myModal">
                  Book this offer
                </button>

                <!-- Modal -->
                <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                  <div class="modal-dialog" role="document">
                    <div class="modal-content">
                      <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="myModalLabel">Book this offer</h4>
                      </div>
                      <div class="modal-body">
                        <%= simple_form_for [@offer, @order] do |f| %>
                          <%= f.input :start_date, as: :string, input_html: { :class => "datepicker", "data-provide" => "datepicker"}, required: true %>
                          <%= f.input :end_date, as: :string, input_html: { :class => "datepicker", "data-provide" => "datepicker"}, required: true %>
                      </div>
                      <div class="modal-footer">
                          <%= f.submit "Book this offer", class: "btn btn-success" %>
                        <% end %>
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                      </div>
                    </div>
                  </div>
                </div>
            <% end %>
            <li>
              <%= link_to "Back", offers_path, class: "btn btn-success" %>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>


<% content_for(:after_js) do %>
  <%= javascript_tag do %>
    $(document).ready(function() {
      var coord = <%= raw @flat_coordinates %>;
      alert('Flat coordinates are ' + coord.lat + ', ' + coord.lng);
    });
  <% end %>
  <script>
    $('.datepicker').datepicker({
      format: "yyyy/mm/dd",
      todayHighlight: true,
      toggleActive: true,
      autoclose: true
    });
  </script>
<% end %>

app/views/orders/index.html.erb
<div class="bg-lighter-grey">
  <div class="container">
    <div class="row">
      <% @orders.each do |order| %>
        <div class="col-xs-12 col-sm-6">
          <div class="card_order">
            <div class="card_link">
              <h3>Booking #<%= order.id%> - <%= link_to order.offer.title, offer_order_path(order.id, order.offer.id) %> </h3>
              <h4> Petsitter:<%= @offer.owner.first_name%></h4>
            <% end %>
          </div>
        </div>


  </div>
</div>

app/views/pages/about.html.erb
<div class= "text-center">
      <h4> A question? A suggestion you want to share with us?</h4>
      <p> contact formulaire </p>
</div>

app/views/shared/_footer.html.erb
<div class="block2 text-center">
  <p>If you want to contact us, we'll be happy to read your <%= link_to about_path do %>message<%end%>. Whant to know better about us? Let's read our <%= link_to story_path do %>story<%end%></p>
</div>

<div class="block3 text-center padded-down">
  <ul class="list-inline">
    <li>
      <a href="" target="_blank"> <i class="fa fa-twitter"></i> Follow us on Twitter</a>
    </li>
    <li>
      <a href="" target="_blank"><i class="fa fa-facebook"></i> See our Facebook's page</a>
    </li>
  </ul>
</div>

app/views/users/show.html.erb
<div class="wrapper">
  <div class="container">
    <div class="row">
      <div class="col-xs-8 col-xs-offset-2 col-sm-6 col-sm-offset-3 col-md-4 col-md-offset-4">
        <div class="text-center padded">
          <div class="profile-card">
            <div class="padded-down">
              <% if current_user.picture? %>
                <%= image_tag current_user.picture, class: "avatar-xl dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
              <% else %>
                <%= image_tag "cat_avatar.jpg", class: "avatar-xl dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
              <% end %>
            </div>
            <p> <%= "#{current_user.first_name} #{current_user.last_name}" %></p>
            <p> <%= current_user.email %> </p>
            <%= link_to edit_user_registration_path do %>
              <p>Modify your profile <i class="fa fa-pencil"></i></p>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="wrapper-grey">
  <div class="container">
    <div class="row">
      <h3 class="text-center padded-xsmall">My Reservations</h3>
      <% current_user.orders.each do |order| %>
      <div class="col-xs-12">
        <div class="product">
          <!-- <div class='product-upvote'>
            <div class="product-arrow"></div>
            <div class='product-count'>95</div>
          </div> -->
          <%= image_tag cloudinary_url(order.offer.photo.path), class:'product-image' %>
          <div class='product-body'>
            <p><%= order.offer.title %></p>
            <!-- <p><%# order.offer.description %></p> -->
            <p><%= order.offer.category %> sitting</p>
            <p><%= order.offer.address %></p>
            <p><%= order.offer.place_type %></p>
            <p><%= order.offer.price %> € / day</p>
          </div>
          <div class="product-controls">
            <ul class="product-right">
              <li><%= order.start_date %></li>
              <li><%= order.end_date %></li>
              <li><%= order.status %></li>
            </ul>
          </div>

        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

<div class="wrapper-grey">
  <div class="container">
    <div class="row">
      <h3 class="text-center padded-xsmall">My Pet sittings</h3>
      <h4 class="text-center">Pending</h4>
      <% current_user.offers.each do |offer| %>
        <% offer.orders.each do |order| %>
          <% if order.status == "pending" %>
            <div class="col-xs-12">
              <div class="product-pending">
                <!-- <div class="product"> -->
                  <!-- <div class='product-upvote'>
                    <div class="product-arrow"></div>
                    <div class='product-count'>95</div>
                  </div> -->
                  <%= image_tag cloudinary_url(order.offer.photo.path), class:'product-image' %>
                  <div class='product-body'>
                    <p><%= order.offer.category %> sitting</p>
                    <p><%= order.offer.address %></p>
                    <p><%= order.offer.place_type %></p>
                    <p><%= order.offer.price %> € / day</p>
                    <p><%= order.start_date %> - <%= order.end_date %></p>
                  </div>
                  <ul class="list-inline product-controls">
                    <%= link_to "Accept", order_accept_path(order), id:"accept" %>
                    <%= link_to "Refuse", order_refuse_path(order), id:"refuse" %>
                    <!-- <li><a href=""><i class="fa fa-star"></i></a></li> -->
                  </ul>
                <!-- </div> -->
              </div>
            </div>
          <% end %>
        <% end %>
      <% end %>
      <h4 class="text-center">Accepted</h4>
      <% current_user.offers.each do |offer| %>
        <% offer.orders.each do |order| %>

          <% if order.status == "accepted" %>
            <div class="col-xs-12">
              <div class="product-accepted">
                <!-- <div class="product"> -->
                  <!-- <div class='product-upvote'>
                    <div class="product-arrow"></div>
                    <div class='product-count'>95</div>
                  </div> -->
                  <%= image_tag cloudinary_url(order.offer.photo.path), class:'product-image' %>
                  <div class='product-body'>
                    <p><%= order.offer.category %> sitting</p>
                    <p><%= order.offer.address %></p>
                    <p><%= order.offer.place_type %></p>
                    <p><%= order.offer.price %> € / day</p>
                    <p><%= order.start_date %> - <%= order.end_date %></p>
                  </div>
                  <ul class="list-inline product-controls">
                    <%= link_to "Refuse", order_refuse_path(order) %>
                    <!-- <li><a href=""><i class="fa fa-star"></i></a></li> -->
                  </ul>
                </div>
              <!-- </div> -->
            </div>
          <% end %>
        <% end %>
      <% end %>
      <h4 class="text-center">Refused</h4>
      <% current_user.offers.each do |offer| %>
        <% offer.orders.each do |order| %>

          <% if order.status == "refused" %>
            <div class="col-xs-12">
              <div class="product-refused">
                <!-- <div class="product"> -->
                  <!-- <div class='product-upvote'>
                    <div class="product-arrow"></div>
                    <div class='product-count'>95</div>
                  </div> -->
                  <%= image_tag cloudinary_url(order.offer.photo.path), class:'product-image' %>
                  <div class='product-body'>
                    <p><%= order.offer.category %> sitting</p>
                    <p><%= order.offer.address %></p>
                    <p><%= order.offer.place_type %></p>
                    <p><%= order.offer.price %> € / day</p>
                    <p><%= order.start_date %> - <%= order.end_date %></p>
                  </div>
                  <div class="product-controls">
                    <ul class="product-right">
                      <li><%= order.status %></li>
                    </ul>
                  </div>
                <!-- </div> -->
              </div>
            </div>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>



<div class="wrapper-grey">
  <div class="container">
    <div class="row">
      <h3 class="text-center padded-xsmall">My Offers of Pet sittings</h3>
      <% current_user.offers.each do |offer| %>
      <div class="col-xs-12">
        <div class="product">
          <!-- <div class='product-upvote'>
            <div class="product-arrow"></div>
            <div class='product-count'>95</div>
          </div> -->
          <%= image_tag cloudinary_url(offer.photo.path), class:'product-image' %>
          <div class='product-body'>
            <p><%= offer.title %></p>
            <!-- <p><%# offer.description %></p> -->
            <p><%= offer.category %> sitting</p>
            <p><%= offer.address %></p>
            <p><%= offer.place_type %></p>

          </div>
          <div class="product-controls">
            <ul class="product-right">
              <li><%= offer.price %> € / day</li>
            </ul>
          </div>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>